services:
  - type: web
    name: fastapi-aqi-api
    env: python
    buildCommand: ""
    startCommand: uvicorn app.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
